config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inventories, only: [:index, :show, :new, :create, :destroy] do
    resources :items, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user

    can :manage, Inventory, author: user
    can :manage, Item, author: user
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :inventory
  belongs_to :item
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :groups, dependent: :destroy
  has_many :items, through: :groups
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :groups, dependent: :destroy
  has_many :inventories, through: :groups
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :inventories

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to inventories_path if user_signed_in?
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @inventories = Inventory.includes([:groups]).where(author: current_user)
  end

  def show
    @inventory = Inventory.find(params[:id])
    @items = @inventory.items.order(created_at: :desc)
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.author = current_user
    if @inventory.save
      redirect_to inventory_path(@inventory)
    else
      render :new
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
    redirect_to inventories_path
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :icon)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @inventory = Inventory.find(params[:inventory_id])
    @item = Item.new
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def create
    @item = Item.new(item_params)
    @item.author = current_user
    @inventory = Inventory.find(params[:inventory_id])
    if params[:inventories_ids]
      params[:inventories_ids].each do |inventory_id|
        inventory = Inventory.find(inventory_id)
        inventory.items << @item
      end
      redirect_to inventories_path
    else
      redirect_to new_inventory_item_path(@inventory)
      nil
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
<header>
  <h1>BUDGET APP</h1>
</header>
<main>
  <div class="logo">
    <%= image_tag("logo.png") %>
  </div>
  <div class="registration">
    <li><%= link_to "Sign up", new_user_registration_path %></li>
    <li><%= link_to "Log in", user_session_path %></li>
  </div>
</main>

app/views/inventories/index.html.erb
<div>
  <header class="inventories">
    <h1>CATEGORIES</h1>
    <ul>
      <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %></li>
    </ul>
  </header>
  <main>
    <div class="items_container">
      <% @inventories.includes([:items]).each do |inventory| %>
        <div class="item">
          <% @total = 0 %>
          <div>
            <img src="<%= inventory.icon %>">
          </div>
          <div>
            <h2><%= link_to inventory.name, inventory_path(inventory) %></h2>
          </div>
          <div>
           <% inventory.items.each do |item| %>
            <% @total += item.amount %>
          <% end %>
          <p><%= @total %></p>
          </div>
          <div>
            <p><%= link_to "X", inventory_path(inventory), data: { turbo_method: :delete } %></p>
          </div>
        </div>
      <% end %>
    </div>
  </main>
  <footer class="index_footer">
    <p><%= link_to "NEW CATEGORY", new_inventory_path %></p>
  </footer>
</div>

app/views/inventories/new.html.erb
<div>
  <header class="inventories_show">
    <h1>NEW CATEGORY</h1>
    <ul>
      <li><%= link_to "<", inventories_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %></li>
    </ul>
  </header>
  <main class="new_inventory">
    <%= form_with model: @inventory do |form| %>
      <div class="name">
        <%= form.label :name %>
        <%= form.text_field :name, placeholder: "Inventory" %>
      </div>
      <div class="name">
        <%= form.label :icon %>
        <%= form.text_field :icon, placeholder: "Link" %>
      </div>
      <footer class="index_footer">
        <div class="actions"><%= form.submit "CREATE CATEGORY" %></div>
      </footer>
    <% end %>
  </main>
</div>

app/views/inventories/show.html.erb
<div>
  <header class="inventories_show">
    <h1>TRANSACTIONS</h1>
    <ul>
      <li><%= link_to "<", inventories_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %></li>
    </ul>
  </header>
  <main>
    <div class="items_container">
      <p>Total <%= @inventory.name %>: $<% @sum=0 %>
      <% @items.each do |item| %>
        <% @sum += item.amount %>
      <% end %>
      <%= @sum %></p>
      <div class="items">
        <% @items.each do |item| %>
          <div class="item">
            <div>
              <p><%= item.name %></p>
            </div>
            <div>
              <p>$<%= item.amount %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </main>
  <footer class="index_footer">
    <p><%= link_to "NEW TRANSACTION", new_inventory_item_path(@inventory) %></p>
  </footer>
</div>

app/views/items/new.html.erb
<div>
  <header class="inventories_new">
    <h1>NEW TRANSACTION</h1>
    <ul>
      <li><%= link_to "<", inventories_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %></li>
    </ul>
  </header>
  <main>
    <div>
      <div class="container">
        <div>
          <%= form_with(model: @item, url: inventory_items_path(@inventory)) do |form| %>
            <div class="form">
              <div class="name">
                <%= form.label :name %>
                <%= form.text_field :name, placeholder: "Item" %>
              </div>
              <div class="amount">
                <%= form.label :amount %>
                <%= form.number_field :amount, placeholder: "Amount" %>
              </div>
            </div>
        </div>
        <div class="check">
          <% @inventories.each do |inventory| %>
            <div>
              <%= inventory.name %>
              <%= check_box_tag "inventories_ids[]", inventory.id, inventory.id == @inventory.id %>
            </div>
          <% end %>
        </div>
      </div>
      <footer class="index_footer">
        <div class="actions"><%= form.submit "CREATE TRANSACTION" %></div>
      </footer>
      <% end %>
    </div>
  </main>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>